### ISSUE TITLE
not for windows?

### ISSUE THREAD

**Issue by j2l** [bahamas10/node-httpserver#1]
>npm install -g httpserver

npm ERR! tar.unpack untar error C:\Users\pm\AppData\Roaming\npm-cache\static-route\0.1.2\package.tgz
C:\Users\pm\AppData\Roaming\npm
`-- (empty)

npm ERR! path C:\Users\pm\AppData\Roaming\npm\node_modules\.staging\static-route-72be9730\test\weird filename$_..
npm ERR! path newline
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\pm\AppData\Roaming\npm\node_modules\.staging\static-route-72be9730\test\weird filename$_..
npm ERR! enoent newline'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by wilcovanesch** [comment]
This happens because one of the dependencies (static-route) has a test that uses a filename with a character (question mark) that's not allowed in Windows. 

You can use my fork which has the question mark taken out by just doing
> npm install -g wilcovanesch/node-httpserver

Alternatively, this more actively maintained package might have the features you need also:
https://github.com/indexzero/http-server

**Comment by j2l** [comment]
Thanks!
It's fixed.
